manifest:
  remotes:
  - name: ren_brewery
    url-base: https://github.com/leocafonso
  defaults:
    remote: ren_brewery
  projects:
  - name: ra_package
    revision: main
    path: modules/ra_package
  - name: cmsis
    revision: main
    path: modules/cmsis
  self:
    path: ren_brewery
    import: submanifests
